### ISSUE TITLE
Tests fail when libstdc++ assertions are enabled

### ISSUE THREAD

**Issue by musicinmybrain** [ctlee/casc#14]
On Fedora Linux 34, with GCC 11.2.1:

```bash
export CXXFLAGS='-Wp,-D_GLIBCXX_ASSERTIONS'
cmake -S . -B build
cmake --build build
./build/test/casctests
```

gives

```
[==========] Running 19 tests from 7 test cases.
[----------] Global test environment set-up.
[----------] 1 test from CASCTestFix
[ RUN      ] CASCTestFix.SimplexIDTraversal
[       OK ] CASCTestFix.SimplexIDTraversal (0 ms)
[----------] 1 test from CASCTestFix (0 ms total)

[----------] 6 tests from CASCTest
[… omitted …]
[----------] 6 tests from CASCTest (2 ms total)

[----------] 5 tests from SimplexSetTest
[… omitted …]
[----------] 5 tests from SimplexSetTest (1 ms total)

[----------] 3 tests from CASCFunctionsTest
[… omitted …]
[----------] 3 tests from CASCFunctionsTest (0 ms total)

[----------] 2 tests from DecimationTest
[ RUN      ] DecimationTest.Decimation
/usr/include/c++/11/array:188: std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](std::array<_Tp, _Nm>::size_type) [with _Tp = int; long unsigned int _Nm = 2; std::array<_Tp, _Nm>::reference = int&; std::array<_Tp, _Nm>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

Trying again with `gdb` gives the following backtrace:

```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
49        return ret;
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:49
#1  0x0000fffff7af07dc in __GI_abort () at abort.c:79
#2  0x0000000000412d20 in std::__replacement_assert(char const*, int, char const*, char const*) ()
#3  0x000000000044bb30 in void casc::visitor_detail::BFS_Up_Node<casc::decimation_detail::InnerVisitor<casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >, 2ul>, casc::visitor_detail::BFS_NoRepeat_Node_Traits, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >, std::integral_constant<unsigned long, 2ul> >::apply<casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >::SimplexID<2ul>*>(casc::decimation_detail::InnerVisitor<casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >, 2ul>&&, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >&, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >::SimplexID<2ul>*, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >::SimplexID<2ul>*) ()
#4  0x000000000044bc98 in void casc::visitor_detail::BFS_Down_Node<casc::decimation_detail::MainVisitor<casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> > >, casc::visitor_detail::BFS_NoRepeat_Node_Traits, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >, std::integral_constant<unsigned long, 2ul> >::apply<casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >::SimplexID<2ul>*>(casc::decimation_detail::MainVisitor<casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> > >&&, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >&, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >::SimplexID<2ul>*, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >::SimplexID<2ul>*) ()
#5  0x000000000044d30c in void casc::decimate<casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >::SimplexID<2ul>, Callback>(casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >&, casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> >::SimplexID<2ul>, Callback<casc::simplicial_complex<casc::detail::simplicial_complex_traits_default<int, int, int, int, int> > >&&) ()
#6  0x0000000000446064 in DecimationTest_Decimation_Test::TestBody() ()
#7  0x0000000000488a18 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
#8  0x000000000047c7f8 in testing::Test::Run() [clone .part.0] ()
#9  0x000000000047cdb4 in testing::TestInfo::Run() [clone .part.0] ()
#10 0x000000000047cfc0 in testing::TestCase::Run() [clone .part.0] ()
#11 0x000000000047dfe4 in testing::internal::UnitTestImpl::RunAllTests() ()
#12 0x000000000047e150 in testing::UnitTest::Run() ()
#13 0x0000000000404b3c in main ()
```

So far, I haven’t put any real time into trying to debug this.

**Comment by ctlee** [comment]
Thanks for filing this issue. The decimation function was comparing to a value just past the end of an array.

**Comment by musicinmybrain** [comment]
Thanks for looking into it!
